spring:
  application:
    name: messenger_server
  datasource:
    url: jdbc:mariadb://localhost:3306/messenger
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
  mybatis:
    mapper-locations: classpath:mappers/*.xml
  sql:
    init:
      encoding: UTF-8

jwt:
  secret: ${JWT_SECRET_KEY}

logging.level.org.springframework.security: DEBUG
